//
// Created by vadim on 26.06.2021.
//

#ifndef ROBOT_PATH_FINDING_ABSTRACTCUSTOMSHAPE_H
#define ROBOT_PATH_FINDING_ABSTRACTCUSTOMSHAPE_H


class AbstractCustomShape {
    
};


#endif //ROBOT_PATH_FINDING_ABSTRACTCUSTOMSHAPE_H
